In [1]:
import torch
import torch.nn as nn
from transformers import CLIPVisionModel, CLIPVisionConfig

# clip_model = torch.nn.Module.load_state_dict('/cognitive_comp/sunrenliang/LLaVA/scripts/v1_5/checkpoints/clip-vit-large-patch14-336/pytorch_model.bin')

# clip_model = torch.load('/cognitive_comp/sunrenliang/LLaVA/scripts/v1_5/checkpoints/clip-vit-large-patch14-336/pytorch_model.bin')

# print(clip_model)
config = CLIPVisionConfig.from_pretrained('/cognitive_comp/sunrenliang/LLaVA/scripts/v1_5/checkpoints/clip-vit-large-patch14-336/config.json')
# moe_clip = CLIPVisionModel.from_pretrained('/cognitive_comp/sunrenliang/LLaVA/scripts/v1_5/checkpoints/clip-vit-large-patch14-336/')
# o
# print(moe_clip)

/home/sunrenliang/miniconda3/envs/qwen-vl/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [16]:
clip_model = torch.load('/cognitive_comp/sunrenliang/LLaVA/scripts/v1_5/checkpoints/clip-vit-large-patch14-336/pytorch_model.bin')

In [17]:
clip_model

OrderedDict([('logit_scale', tensor(4.6052)),
             ('text_model.embeddings.position_ids',
              tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                       72, 73, 74, 75, 76]])),
             ('text_model.embeddings.token_embedding.weight',
              tensor([[-0.0015,  0.0360,  0.0223,  ...,  0.0148,  0.0045, -0.0214],
                      [ 0.0148,  0.0261, -0.0127,  ..., -0.0042,  0.0012,  0.0113],
                      [-0.0139, -0.0134,  0.0056,  ..., -0.0198, -0.0135, -0.0036],
                      ...,
                      [ 0.0095, -0.0022, -0.0143,  ..., -0.0080, -0.0204,  0.0109],
                      [ 0.0012,  0.0032,  0.0003, 

In [19]:
clip_model['text_model.embeddings.position_ids']

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76]])

In [23]:
moe = CLIPVisionModel(config=config)

In [32]:
moe.save_pretrained('./tmp')

In [33]:
torch.save(moe.parameters, '/home/sunrenliang/miniconda3/envs/qwen-vl/lib/python3.10/site-packages/transformers/models/clip/pytorch_model.bin')

In [43]:
t = moe.state_dict()
# for k,v in t.items():
#     if k not in clip_model:
#         t['k'] = clip_model['']

#     else:
#         t['k'] = clip_model[k]
torch.save(t, '/home/sunrenliang/miniconda3/envs/qwen-vl/lib/python3.10/site-packages/transformers/models/clip/pytorch_model.bin')


In [44]:
moe_test = torch.load('/home/sunrenliang/miniconda3/envs/qwen-vl/lib/python3.10/site-packages/transformers/models/clip/pytorch_model.bin')
moe_test

OrderedDict([('vision_model.embeddings.class_embedding',
              tensor([ 0.0243, -0.0192, -0.0533,  ..., -0.0396, -0.0213,  0.0090])),
             ('vision_model.embeddings.patch_embedding.weight',
              tensor([[[[-9.1668e-03, -2.4431e-02, -2.1405e-02,  ..., -6.3146e-03,
                          9.1052e-03,  1.7885e-02],
                        [-1.6578e-02,  1.7199e-02,  3.4435e-02,  ..., -1.0385e-03,
                         -1.6897e-02, -1.9531e-02],
                        [-2.0459e-02, -3.4265e-03,  2.7590e-02,  ...,  9.7059e-03,
                          1.2536e-02,  8.7357e-03],
                        ...,
                        [-2.5005e-02,  1.4382e-02,  4.5360e-03,  ...,  5.9559e-03,
                          3.4819e-02, -3.7266e-04],
                        [ 1.3204e-02,  2.5783e-02, -3.3554e-02,  ...,  1.3068e-02,
                         -2.2371e-02, -3.0020e-02],
                        [ 2.8241e-02, -2.1114e-02,  2.2017e-03,  ...,  1.4527e-02,
       